### ISSUE TITLE
Downgrading phpunit?

### ISSUE THREAD

**Issue by diegoacuna** [krzysiekpiasecki/Gentelella#19]
Hi, nice work on this repo. I have installed on my machine php 5.5.25 and by default the composer file on the repo doesn't work because phpunit 5.0 requires at least php 5.6. I've changed phpunit version to ^4.8.0 with no errors on composer update/install and on:

    php ./vendor/bin/phpunit

Maybe to extend support to php >= 5.5.9 is an option to downgrade phpunit to ^4.8.0?

**Comment by krzysiekpiasecki** [comment]
How is it possible? Required dependency is just a "php >=5.5.9".

**Comment by krzysiekpiasecki** [comment]
I decided to upgrade php to next minor release. Security Support for this branch will expire in 1 month.

Thanks @diegoacuna

**Comment by krzysiekpiasecki** [comment]
@diegoacuna Finally i follow your advice and symphony. The change was made at 1.3.0.

Thanks :)
