### ISSUE TITLE
When install it, the vendors folder does not exist

### ISSUE THREAD

**Issue by Saint-Cyr** [krzysiekpiasecki/Gentelella#21]
After installation (both for composer & git) the vendor folder (./web/assets/vendors) does not exist and this cause the application view to do not reflect the the demo (js, and some css are not working ....) and as I see bower.json file in the root of the project, I try `bower install` but still without success the bower installation looks like it finish fine but the configured folder in .bowerrc, indeed, the vendor file `{
  "directory" : "web/assets/vendors"
}` is not created at all.... then I cannot enjoy the app. 

Solved: I solve the issue (bad way) by cloning the original Gentelella repository and copy it vendors folder to the location of Symfony app manually...

**Comment by krzysiekpiasecki** [comment]
It looks like a local issue.

- Did you try to install bower dependencies as root with a verbose mode? See command line help.
- Did you check for a global bower configuration?

**Comment by Saint-Cyr** [comment]
You might be right because I'm not really familiarized with bower. But I'll check it later thank you.
