### ISSUE TITLE
Registering a new user

### ISSUE THREAD

**Issue by krzysiekpiasecki** [krzysiekpiasecki/Gentelella#30]
Block or implement 

register/

**Comment by MedUnes** [comment]
The route is already working
http://gentelella.herokuapp.com/register/

Could you clarify the needed enhancement please ?

**Comment by krzysiekpiasecki** [comment]
- No templating,
- 403 after login but it's a secure area, so maybe forwarding a new user to a public resources.

**Comment by MedUnes** [comment]
I made a PR [here](https://github.com/krzysiekpiasecki/Gentelella/pull/54), it works allright for me.
Waiting for confirmations

P.S: further features maight be added later (email confirmation, password reset)

**Comment by krzysiekpiasecki** [comment]
Registration is successful (your fork). After testing and merging #54 feel free to implements this features. Now you can safely close this issue.

@MedUnes thanks.

**Comment by krzysiekpiasecki** [comment]
Now I can close this ticket and working with your PR. Thanks again.
