### ISSUE TITLE
responsiveness issue in tables_dynamic page 

### ISSUE THREAD

**Issue by MedUnes** [krzysiekpiasecki/Gentelella#34]
There is a responsiveness issue at [this page](https://colorlib.com/polygon/gentelella/tables_dynamic.html)

As you can see in the screenshot below, the Datatables widget overflows the main content section
![image](https://cloud.githubusercontent.com/assets/8580094/21743703/096d35ac-d508-11e6-8cf7-99a9ed8fc164.png)

To reproduce this issue open [this link](https://colorlib.com/polygon/gentelella/tables_dynamic.html
) either in a mobile device or in google chrome and then simulate a mobile device in the inspector (F12)

**Comment by krzysiekpiasecki** [comment]
I have recreated.

These types of problems are beyond the scope of this repository. Every time there is a new version of the original template this repository is updated and new minor version is released.

Unfortunately I'm waiting for a new version for a long time.

Thanks @MedUnes  Let me do not close this issue until it will be patch at the source.

**Comment by MedUnes** [comment]
great.  i will try to fix it by myself anyway as it is a real problem for any production

**Comment by MedUnes** [comment]
https://github.com/puikinsh/gentelella/pull/359

**Comment by krzysiekpiasecki** [comment]
Probably resolved. Waiting for next minor release of gentelella.

@MedUnes thanks for a reporting this issues and your contribution.
