### ISSUE TITLE
Bad DB Credentials and no errors

### ISSUE THREAD

**Issue by ousamabenyounes** [krzysiekpiasecki/Gentelella#51]
Hi @krzysiekpiasecki ,

I'm beginning using your gentelella symfony ready to use skeleton application...
Thanks a lot again for all the team for your really nice work :).
I installed this repository. I ran doctrine commands, but my credentials were wrong.
No errors occured. Maybe we should try to check if db credentials are ok before running all scripts.

So I got "Database has been created ..." which was a wrong information when I checked the database.

` <exec command="php bin/console doctrine:database:create --if-not-exists"/>
<echo msg="Database has been created ..." />`

Regards,
Ousama.

**Comment by krzysiekpiasecki** [comment]
Run the command ```php vendor/bin/phing -verbose```

You should see then such an exception
> -- [Doctrine\DBAL\Driver\PDOException] [exec]   SQLSTATE[HY000]: General error: 1364 Field 'locked' doesn't have a default value

It comes from UserBundle library.

**Comment by ousamabenyounes** [comment]
Thank you for this feedback.
I was just asking if it was possible to add check on build. 
If a step fail then tell user stepXXXX failed :).

I will have a look on it and if I have some news I'll open a pull request.

Regards

**Comment by krzysiekpiasecki** [comment]
@ousamabenyounes  At the moment ```--verbose``` parameter is the only road map. PR always welcome.

May I ask you that you close this ticket if you haven't got any notices?

**Comment by ousamabenyounes** [comment]
Thank you for your feedback
