### ISSUE TITLE
Add a minimal documentation

### ISSUE THREAD

**Issue by MedUnes** [krzysiekpiasecki/Gentelella#53]
I think a minimal documentation is necessary on how to build using composer, bower and phing..

**Comment by krzysiekpiasecki** [comment]
You mean it's a too tiny documentation?

```
composer create-project krzysiekpiasecki/gentelella gentelella "dev-master"
$ cd gentelella
$ composer setup
$ composer test
$ php bin/console fos:user:create
$ php bin/console server:run 127.0.0.1:8080 --env=prod
```

**Comment by MedUnes** [comment]
No, this should be allright, though it must be published on the readme.md or a .rst file, as some developers might be beginners..

**Comment by MedUnes** [comment]
I am sorry, didn't notice the link, it is ok, thanks.

**Comment by krzysiekpiasecki** [comment]
@MedUnes I've added a INSTALL file following your issue. If you haven't got any further notices please close this ticket.

Who opens a ticket MUST close this ticket :)

PS Maybe you can first test the commands from INSTAL file in the windows terminal?

**Comment by krzysiekpiasecki** [comment]
@MedUnes Do you work on WIN OS?

**Comment by ahamedifham** [comment]
[InvalidArgumentException]
  Could not find package krzysiekpiasecki/gentelella with version dev-master in a version installable using your PHP
  version 5.6.25.

I am getting this error when I try to install from Composer in windows. How should I tackle it?

**Comment by krzysiekpiasecki** [comment]
This app requires PHP7.

Look at: 
https://github.com/krzysiekpiasecki/Gentelella/blob/master/composer.json
