### ISSUE TITLE
(CI) php-cs-fixer must return non-zero value when no CS

### ISSUE THREAD

**Issue by krzysiekpiasecki** [krzysiekpiasecki/Gentelella#55]
PHP-CS-FIXER must return non-zero value:
https://travis-ci.org/krzysiekpiasecki/Gentelella/jobs/241787978

**Comment by MedUnes** [comment]
> The command "./vendor/bin/phpunit" exited with 0.
As I know, this means the build passes and no  errors were found in analyzed code.
Could you explain please?

**Comment by krzysiekpiasecki** [comment]
It's about coding standard fixer not php unit.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Orange network.                                                                                                                                                                                                                From: MedUnesSent: poniedziałek, 12 czerwca 2017 13:32To: krzysiekpiasecki/GentelellaReply To: krzysiekpiasecki/GentelellaCc: Krzysztof Piasecki; AuthorSubject: Re: [krzysiekpiasecki/Gentelella] (CI) php-cs-fixer must return non-zero value (#55)
The command "./vendor/bin/phpunit" exited with 0.
As I know, this means the build passes and no  errors were found in analyzed code.
Could you explain please?


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/krzysiekpiasecki/Gentelella","title":"krzysiekpiasecki/Gentelella","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/krzysiekpiasecki/Gentelella"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MedUnes in #55: \u003e The command \"./vendor/bin/phpunit\" exited with 0.\r\nAs I know, this means the build passes and no  errors were found in analyzed code.\r\nCould you explain please?"}],"action":{"name":"View Issue","url":"https://github.com/krzysiekpiasecki/Gentelella/issues/55#issuecomment-307763874"}}}

**Comment by MedUnes** [comment]
I think it is fixed right now.

**Comment by krzysiekpiasecki** [comment]
@MedUnes fixed now with https://github.com/krzysiekpiasecki/Gentelella/commit/237994d13a0e80c056255be5376d2138567eedd7

Test
https://travis-ci.org/krzysiekpiasecki/Gentelella/jobs/242332520
