### ISSUE TITLE
Scenarios of real-life application

### ISSUE THREAD

**Issue by MedUnes** [krzysiekpiasecki/Gentelella#56]
To demonstrate the strength of Symfony, what about developing a real-life application (chat, commerce, erp, etc.) that will handle real data and use the templates pages without sticking to them literaly

**Comment by krzysiekpiasecki** [comment]
It's a natural step in developing an application, making a step towards a domain, but it's requires sticking to a full technological stack, using a domain use cases and therefore based on my experience it's a hard work and gives a relative small benefits for the community.

Currently this repository aims to be a startup with no or minimal domain logic inside, based on SF and G, published to quickly start testing or developing a domain application or solutions.

But of course any idea and PR are always welcome. If you haven't go any notices please close this ticket @MedUnes.
