### ISSUE TITLE
lost command in code ? ...

### ISSUE THREAD

**Issue by o-Fred-o** [krzysiekpiasecki/Gentelella#69]
Hello,
I'm looking at your project, and i found in https://github.com/krzysiekpiasecki/Gentelella/blob/master/app/Resources/views/gentelella/calendar.html.twig on line 48, some lost command line code ... ?

**Comment by krzysiekpiasecki** [comment]
Resolved with 7143a5d1730209ff660aede861da0e31f57db3d1. @o-Fred-o thanks.
