### ISSUE TITLE
There are no commands defined in the "server" namespace

### ISSUE THREAD

**Issue by Nearby1019** [krzysiekpiasecki/Gentelella#70]
run php bin/console server:run 127.0.0.1:8080 --env=prod 
error Message: "There are no commands defined in the "server" namespace."

**Comment by krzysiekpiasecki** [comment]
Thanks for your reporting. PHP bundled web server is only available in dev environment. 
Fixed at 30d70ddbc82bf810e785cacbe308948a4b7d85b5.
